language: php
os: linux
php:
  - 7.1
  - 7.2
  - 7.3

install:
  # Install composer packages, will also trigger dump-autoload
  - composer self-update
  - composer install --no-interaction --ignore-platform-reqs

before_script:
  - composer require friendsofphp/php-cs-fixer

script:
  - composer validate
  - phpunit
  - PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix . --verbose --diff --dry-run

cache:
  directories:
    - $HOME/.php-cs-fixer

matrix:
  fast_finish: true
